# Generated by Django 2.0.5 on 2018-05-30 00:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.blog_image_uh),
        ),
    ]
