# Generated by Django 2.0.5 on 2018-05-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180530_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='alt_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
