# Generated by Django 2.0.5 on 2018-05-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_blog_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fitness_library',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
