# Generated by Django 2.0.5 on 2018-06-05 23:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_shopitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='img',
            field=models.ImageField(null=True, upload_to=accounts.models.product_img_uh),
        ),
    ]
