# Generated by Django 2.0.5 on 2018-06-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180605_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='alt_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
