# Generated by Django 2.0.5 on 2018-06-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_shopitem_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
