# Generated by Django 2.0.5 on 2018-06-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180607_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
