# Generated by Django 2.0.5 on 2018-07-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180607_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='store_button',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
