# Generated by Django 2.0.5 on 2018-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_shopitem_store_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('item_name', models.CharField(max_length=500)),
            ],
        ),
    ]
