# Generated by Django 2.0.5 on 2018-08-13 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_buyerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerresponse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 19, 2, 18, 766065, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
